spring:
  datasource:
    url: jdbc:h2:mem:lg-test
    username: lg
    password: laundryGo!
    hikari:
      maximum-pool-size: 4
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
logging:
  level:
    root: info
    com.laundrygo.shorturl.repository: debug